<?php 
$cars = [
  [
    'id' => 1,
    'model' => 'Model3',
    'img' => 'https://tesla-cdn.thron.com/delivery/public/image/tesla/457dd9fa-6e32-43b1-a6cf-9b3d76e9e181/bvlatuR/std/2232x720/global-order-hero',
    'brand' => 'Tesla',
    'motor' => 'Electric',
    'displacement' => 2200,
    'priceXday' => 530,
    'color' => 'Black',
    'yearOfregistration' => 2019,
    'asset' => 'Sports trim',
    'places' => 5,
    'doors' => 5,
    'insurance' => 'included',
  ],
  [
    'id' => 2,
    'model' => 'Cybertruck',
    'img' => 'https://cdn.dmove.it/images/20849/CyberMain.jpg',
    'brand' => 'Tesla',
    'motor' => 'Electric',
    'displacement' => 2600,
    'priceXday' => 700,
    'color' => 'Gray',
    'yearOfregistration' => 2020,
    'asset' => 'Suv',
    'places' => 7,
    'doors' => 4,
    'insurance' => 'included',
  ],
  [
    'id' => 3,
    'model' => 'Fiesta',
    'img' => 'https://cdn.motor1.com/images/mgl/9Yv30/s3/ford-fiesta-st-line-2022.jpg',
    'brand' => 'Ford',
    'motor' => 'Diesel',
    'displacement' => 1400,
    'priceXday' => 150,
    'color' => 'White',
    'yearOfregistration' => '2021',
    'asset' => 'Utilitaries',
    'places' => 5,
    'doors' => 5,
    'insurance' => 'not included',
  ],
  [
    'id' => 4,
    'model' => 'Q8 Premium',
    'img' => 'https://www.ccarprice.com/products/Audi-Q8-Premium-55-TFSI-qua.jpg',
    'brand' => 'Audi',
    'motor' => 'Gas',
    'displacement' => 2000,
    'priceXday' => 450,
    'color' => 'Metallic orange',
    'yearOfregistration' => 2021,
    'asset' => 'Suv',
    'places' => 5,
    'doors' => 5,
    'insurance' => 'included',
  ],
  [
    'id' => 5,
    'model' => 'Kangoo',
    'img' => 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Renault_Kangoo_I_front_20090121.jpg',
    'brand' => 'Reanult',
    'motor' => 'Petrol',
    'displacement' => 1200,
    'priceXday' => 60,
    'color' => 'Yellow',
    'yearOfregistration' => 2005,
    'asset' => 'Utilitaries',
    'places' => 5,
    'doors' => 5,
    'insurance' => 'included',
  ],
  [
    'id' => 6,
    'model' => 'McLaren 720s',
    'img' => 'https://www.autoblog.it/app/uploads/2020/06/8720slemansmclarenorangefront3-4.jpg',
    'brand' => 'Petrol',
    'displacement' => 2800,
    'priceXday' => 1000,
    'color' => 'Orange',
    'yearOfregistration' => 2020,
    'asset' => 'Sports trim',
    'places' => 2,
    'doors' => 3,
    'insurance' => 'included',
  ],
  [
    'id' => 7,
    'model' => 'T-Roc',
    'img' => 'https://cdn.motor1.com/images/mgl/VPPPl/s1/volkswagen-t-roc-r-2022.jpg',
    'brand' => 'Volkswagen',
    'motor' => 'Gas',
    'displacement' => 1800,
    'priceXday' => 370,
    'color' => 'Blue',
    'yearOfregistration' => 2022,
    'asset' => 'Suv',
    'places' => 5,
    'doors' => 5,
    'insurance' => 'not included',
  ],
  [
    'id' => 8,
    'model' => '500',
    'img' => 'https://statics.quattroruote.it/content/dam/quattroruote/it/foto/2021/09/22/fiat_500_red_2021_/gallery/rbig/2021-fiat-500-red-01.jpg',
    'brand' => 'Fiat',
    'motor' => 'Electric',
    'displacement' => 1600,
    'priceXday' => 230,
    'color' => 'Red',
    'yearOfregistration' => 2020,
    'asset' => 'Utilitaries',
    'places' => 4,
    'doors' => 3,
    'insurance' => 'included',
  ],
  [
    'id' => 9,
    'model' => 'Twingo',
    'img' => 'https://immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2014/09/renault_twingo_post.png?itok=q76DEM8w',
    'brand' => 'Renault',
    'motor' => 'Petrol',
    'displacement' => 1400,
    'priceXday' => 100,
    'color' => 'Lightblue',
    'yearOfregistration' => 2019,
    'asset' => 'Utilitaries',
    'places' => 4,
    'doors' => 5,
    'insurance' => 'not included',
  ],
  [
    'id' => 10,
    'model' => 'Phantom',
    'img' => 'https://www.autoscout24.it/assets/auto/images/model/rolls-royce/rolls-royce-phantom/rolls-royce-phantom-l-01.jpg',
    'brand' => 'Rolls-Royce',
    'motor' => 'Petrol',
    'displacement' => 1800,
    'priceXday' => 1200,
    'color' => 'Metallic silver',
    'yearOfregistration' => 2021,
    'asset' => 'Sports trim',
    'places' => 5,
    'doors' => 5,
    'insurance' => 'included',
  ],
];
?>